# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

     sh "your_script.sh"
     You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease", project_dir: 'android/', flavor: "full", flags: "-t lib/main-full.dart")
    upload_to_play_store(
      skip_upload_changelogs: true
    )
  end

  desc "Build APK with flavor foss"
  lane :build_foss do
    gradle(task: "clean assembleFossRelease", project_dir: 'android/', flags: "-t lib/main-foss.dart")
  end

  desc "Build APK with flavor full"
  lane :build_full do
    gradle(task: "clean assembleFullRelease", project_dir: 'android/', flags: "-t lib/main-full.dart")
  end
end
