# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy to closed beta track"
  lane :closed_beta do
    begin
      gradle(task: "clean")
      sh("flutter", "build", "appbundle", "--flavor", "full", "-t", "lib/main_full.dart")
      upload_to_play_store(
        track: 'beta',
        aab: './build/app/outputs/bundle/release/app-full-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"],
      )
    end
  end

  desc "Build AppBundle with flavor foss"
  lane :build_foss_appbundle do
    sh("flutter", "build", "appbundle", "--flavor", "foss", "-t", "lib/main_foss.dart")
  end

  desc "Build APK with flavor foss"
  lane :build_foss_apk do
    sh("flutter", "build", "apk", "--flavor", "foss", "-t", "lib/main_foss.dart")
  end
end
