/// Flutter icons PrivacyBlur
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PrivacyBlur
///      fonts:
///       - asset: fonts/PrivacyBlur.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PrivacyBlurIcons {
  PrivacyBlurIcons._();

  static const _kFontFam = 'PrivacyBlur';
  static const String? _kFontPkg = null;

  static const IconData shape =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData granularity =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
